#!/bin/bash

#------------------------------------------------------------------------------
function _abort {
	echo -e "\nABORT: $1\n\n"
	exit 1
}


#
# M A I N
#

if test -z "$DB_NAME" && ! test -z "$1"; then
	DB_NAME="$1"
fi

if test -z "$DB_PASS" && ! test -z "$2"; then
	DB_PASS="$2"
fi

if test -z "$DB_NAME"; then
	_abort "export DB_NAME or call: $0 NAME PASS"
fi

if test -z "$DB_PASS"; then
	_abort "export DB_PASS or call: $0 NAME PASS"
fi


if test -d "/var/lib/mysql/$DB_NAME"; then
	_abort "database $DB_NAME exists already - call: DROP DATABASE $DB_NAME"
fi

echo "create database $DB_NAME"
echo "CREATE DATABASE $DB_NAME" | mysql -u root

echo "create database $DB_NAME account $DB_NAME:$DB_PASS"
echo "GRANT ALL PRIVILEGES ON $DB_NAME.* TO '$DB_NAME'@'%' IDENTIFIED BY '$DB_PASS'" | mysql -u root

